name: Build & Publish ResellKit Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-resellkit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download ResellKit AppImage
        run: |
          curl -L -o ResellKit-x86_64.AppImage https://resellkit.app/download/latest/resellkit-1.5.42-x86_64.AppImage
          chmod +x ResellKit-x86_64.AppImage
          ./ResellKit-x86_64.AppImage --appimage-extract
          mv squashfs-root resellkit-extracted

      - name: Build Docker Image
        run: |
          docker build -t resellkit-docker .

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Tag & Push Docker Image
        run: |
          docker tag resellkit-docker queball1999/resellkit-docker:latest
          docker push queball1999/resellkit-docker:latest
